// prompts/audit.js
// v3.3 — Delegates to skill modules. Kept for backward compatibility.

import {
    SKILL_COHERENCE_AUDIT,
    SKILL_MES_EXAMPLE_AUDIT,
    SKILL_SMART_SUGGESTIONS,
    SKILL_CONFLICT_CHECK,
    SKILL_CARD_REVIEW,
    SKILL_DEPTH_ANALYSIS,
    SKILL_STYLE_CONSISTENCY,
    SKILL_CROSS_REF,
} from './skills/phase-audit.js';

export const COHERENCE_AUDIT_PROMPT       = SKILL_COHERENCE_AUDIT;
export const MES_EXAMPLE_AUDIT_PROMPT     = SKILL_MES_EXAMPLE_AUDIT;
export const SMART_SUGGESTION_CHECK_PROMPT = SKILL_SMART_SUGGESTIONS;
export const CONFLICT_CHECK_PROMPT        = SKILL_CONFLICT_CHECK;
export const CARD_REVIEW_PROMPT           = SKILL_CARD_REVIEW;
export const DEPTH_ANALYSIS_PROMPT        = SKILL_DEPTH_ANALYSIS;
export const STYLE_CONSISTENCY_PROMPT     = SKILL_STYLE_CONSISTENCY;
export const CROSS_REF_PROMPT             = SKILL_CROSS_REF;
