// prompts/audit.js
// v3.0 — Delegates to skill modules. Kept for backward compatibility.

import {
    SKILL_COHERENCE_AUDIT,
    SKILL_MES_EXAMPLE_AUDIT,
    SKILL_SMART_SUGGESTIONS,
    SKILL_CONFLICT_CHECK,
    SKILL_CARD_REVIEW,
} from './skills/phase-audit.js';

export const COHERENCE_AUDIT_PROMPT = SKILL_COHERENCE_AUDIT;
export const MES_EXAMPLE_AUDIT_PROMPT = SKILL_MES_EXAMPLE_AUDIT;
export const SMART_SUGGESTION_CHECK_PROMPT = SKILL_SMART_SUGGESTIONS;
export const CONFLICT_CHECK_PROMPT = SKILL_CONFLICT_CHECK;
export const CARD_REVIEW_PROMPT = SKILL_CARD_REVIEW;
